apiVersion: v1
kind: Namespace
metadata:
  name: thomptyler-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: thomptyler-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: thomptyler/flaskapp
        image: thomptyler/flaskapp
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

---
